CREATE TABLE operatives (id INTEGER, name TEXT, birthday DATE, PRIMARY KEY(id));
INSERT INTO operatives (id, name, birthday) VALUES (1, "Michael Arthur Long", "1949-01-09");
INSERT INTO operatives (id, name, birthday) VALUES (2, "Devon Miles", "1942-07-12");
INSERT INTO operatives (id, name, birthday) VALUES (3, "Dr. Bonnie Barstow", "1954-11-24");
INSERT INTO operatives (id, name, birthday) VALUES (4, "Reginald Cornelius III", "1952-05-04");
UPDATE operatives SET name = "Michael Knight" WHERE id = 1;
ALTER TABLE operatives ADD COLUMN occupation TEXT;
UPDATE operatives SET occupation = "Field Agent" WHERE id = 1;
UPDATE operatives SET occupation = "Head of Operations" WHERE id = 2;
UPDATE operatives SET occupation = "Technician" WHERE id = 3;
UPDATE operatives SET occupation = "Truck Driver" WHERE id = 4;
DELETE FROM operatives WHERE id = 3;
INSERT INTO operatives (id, name, birthday, occupation) VALUES (5, "April Curtis", "1952-05-04", "Senior Design Officer");
SELECT * FROM operatives;